server:
  port: 8082  # auth server porti

spring:
  application:
    name: appeal  # Application nomi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server manzili
  instance:
    prefer-ip-address: true # IP manzilni o'zi tanlasin