server:
  port: 0  # Auth server porti
  tomcat:
    max-http-form-post-size: 50MB # Maksimal HTTP POST so‘rov hajmi
    max-swallow-size: 50MB        # Maksimal swallow buffer
  undertow:
    buffer-size: 1024             # Undertow buffer o‘lchami
    direct-buffers: true          # Direct buffer'larni yoqish

spring:
  application:
    name: youTube  # Application nomi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/youtube
    username: postgres
    password: 1
    hikari:
      maximum-pool-size: 10  # HikariCP uchun max pool size
      minimum-idle: 2        # Minimal ulanishlar soni
      idle-timeout: 30000    # Bo'sh turgan ulanishlar uchun timeout
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update  # DDL avtomatik yangilash
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use-new-id-generator-mappings: true
  data:
    rest:
      base-path: /api
  servlet:
    multipart:
      max-file-size: 100MB         # Maksimal yuklanadigan fayl hajmi
      max-request-size: 100MB      # Maksimal so‘rov hajmi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
