server:
  port: 8080  # Gateway uchun port

spring:
  application:
    name: gateway  # Gateway uchun application nomi

  cloud:
    gateway:
      globalcors: # Barcha servislarga ruxsat berish
        corsConfigurations:
          '[/**]':
            allowedOrigins:
#            "http://localhost:3000"       # Barcha originlarga ruxsat berish
                - "http://localhost:3000"       # Barcha originlarga ruxsat berish
                - "http://192.168.10.181:3000"  # Barcha originlarga ruxsat berish
            allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowedHeaders: "*"  # Barcha headerlarga ruxsat berish
            allowCredentials: true  # Credentiallarni ruxsat berish


      routes:
        - id: auth-service
          uri: lb://auth  # Load balancer orqali auth servisi
          predicates:
            - Path=/auth/**  # Auth servisi uchun yo'nalishlar
          filters:
            - RewritePath=/auth/(?<remaining>.*), /${remaining}  # /auth ni olib tashlaydi

        - id: appeal-service
          uri: lb://appeal  # Load balancer orqali appeal servisi
          predicates:
            - Path=/appeal/**  # Appeal servisi uchun yo'nalishlar
          filters:
#            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/appeal/(?<remaining>.*), /${remaining}  # /appeal ni olib tashlaydi

        - id: python_translate-service
          uri: lb://python_translate  # Load balancer orqali python-translate servisi
          predicates:
            - Path=/python_translate/**  # Python_translate servisi uchun yo'nalishlar
          filters:
#            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/python_translate/(?<remaining>.*), /${remaining}  # /python_translate ni olib tashlaydi

        - id: parsing-service
          uri: lb://parsing  # Load balancer orqali parsing servisi
          predicates:
              - Path=/parsing/**  # Parsing servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/parsing/(?<remaining>.*), /${remaining}  # /parsing ni olib tashlaydi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server manzili
  instance:
    prefer-ip-address: true # IP manzilni o'zlashtirish

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Gateway loglari