server:
  port: 8080  # Gateway uchun port
  forward-headers-strategy: framework

spring:
  main:
    allow-circular-references: true
  application:
    name: gateway  # Gateway uchun application nomi

  cloud:
    gateway:
      httpclient:
        response-timeout: 600s  # HTTP so‘rovlar uchun timeout
      httpserver:
        wiretap: true  # Wiretapni yoqish
      globalcors: # Barcha servislarga ruxsat berish
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
#            "http://localhost:3000"       # Barcha originlarga ruxsat berish
                - "http://192.168.10.181:3000"  # Barcha originlarga ruxsat berish
                - "http://localhost:3000"       # Barcha originlarga ruxsat berish
                - "http://localhost:3001"
                - "http://192.168.10.181:3001"  # Barcha originlarga ruxsat berish
                - "http://192.168.10.172:3000"  # Barcha originlarga ruxsat berish
            allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
            allowedHeaders: "*"  # Barcha headerlarga ruxsat berish
            allowCredentials: true  # Credentiallarni ruxsat berish


      routes:
        - id: auth-service
          uri: lb://auth  # Load balancer orqali auth servisi
          predicates:
            - Path=/auth/**  # Auth servisi uchun yo'nalishlar
          filters:
            - RewritePath=/auth/(?<remaining>.*), /${remaining}  # /auth ni olib tashlaydi
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter

        - id: appeal-service
          uri: lb://appeal  # Load balancer orqali appeal servisi
          predicates:
            - Path=/appeal/**  # Appeal servisi uchun yo'nalishlar
          filters:
#            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/appeal/(?<remaining>.*), /${remaining}  # /appeal ni olib tashlaydi

        - id: python_translate
          uri: http://localhost:5000  # Load balancer orqali python-translate servisi
#          uri: lb://pythonTranslate  # Load balancer orqali python-translate servisi
          predicates:
            - Path=/python_translate/**  # Python_translate servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/python_translate/(?<remaining>.*), /${remaining}  # /python_translate ni olib tashlaydi

        - id: parsing-service
          uri: lb://parsing  # Load balancer orqali parsing servisi
          predicates:
              - Path=/parsing/**  # Parsing servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/parsing/(?<remaining>.*), /${remaining}  # /parsing ni olib tashlaydi

        - id: appStore
          uri: lb://appStore  # Load balancer orqali app_store servisi
          predicates:
              - Path=/appStore/**  # App_store servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/appStore/(?<remaining>.*), /${remaining}  # /app_store ni olib tashlaydi


        - id: notes
          uri: lb://notes  # Load balancer orqali notes servisi
          predicates:
              - Path=/notes/**  # Notes servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/notes/(?<remaining>.*), /${remaining}  # /notes ni olib tashlaydi


        - id: telephone
          uri: lb://telephone  # Load balancer orqali telephone servisi
          predicates:
              - Path=/telephone/**  # Telephone servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/telephone/(?<remaining>.*), /${remaining}  # /telephone ni olib tashlaydi


        - id: youTube
          uri: lb://youTube  # Load balancer orqali youTube servisi
          predicates:
              - Path=/youTube/**  # You_tube servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/youTube/(?<remaining>.*), /${remaining}  # /youTube ni olib tashlaydi


        - id: library
          uri: lb://library  # Load balancer orqali youTube servisi
          predicates:
              - Path=/library/**  # library servisi uchun yo'nalishlar
          filters:
            - AuthenticationFilter  # Auth servisi orqali tekshirish uchun filter
            - RewritePath=/library/(?<remaining>.*), /${remaining}  # /library ni olib tashlaydi



      default-filters: # Barcha servislarga ruxsat berish
        - name: RequestSize
          args:
            maxSize: 10GB
  codec:
    max-in-memory-size: 5GB


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server manzili
  instance:
    prefer-ip-address: true # IP manzilni o'zlashtirish

logging:
  level:
    org.springframework.cloud.gateway: DEBUG  # Gateway loglari
    org.springframework.web: DEBUG