server:
  port: 0  # Auth server porti

spring:
  application:
    name: app_store  # Application nomi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/app_store
    username: postgres
    password: 1
    hikari:
      maximum-pool-size: 10  # HikariCP uchun max pool size
      minimum-idle: 2        # Minimal ulanishlar soni
      idle-timeout: 30000    # Bo'sh turgan ulanishlar uchun timeout
      pool-name: HikariPool-1
  jpa:
    hibernate:
      ddl-auto: update  # DDL avtomatik yangilash
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        use-new-id-generator-mappings: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
